---
title             : "A Computational Perspective On Spatial Perspective Transformations: From Sensory Inference To Imagined Self-motion"
shorttitle        : "A Computational Perspective"

author: 
  - name          : "Andrew W. Ellis"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Fabrikstrasse 8, 3012 Bern, Switzerland"
    email         : "andrew.ellis@psy.unibe.ch"
  - name          : "Fred W. Mast"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "Department of Psychology, University of Bern"


author_note: >
  Andrew W. Ellis, Fred W. Mast, Department of Psychology.
  
  AE and FM planned and conducted the research; AE and FM analyzed the data and wrote the manuscript.
  
  Raw data and analysis scripts are available at https://osf.io/u26mq.


abstract: >
    Recent research showed the involvement of vestibular information in cognitive processes. We provide a computational framework for vestibular cognition and thereby focus on perspective transformations, which require a simulated rotation of the self. We explore how the ability to model the effects of body rotation using vestibular input might enable the ability to imagine body rotations. We approach this problem by considering a simple agent endowed with a complex statistical model of the hidden causes of its sensory input. We explain how this statistical model enables the agent to predict its sensory input and hidden sensory variables. Based on a probabilistic graphical model, we formalize qualitative concepts of mental simulation. Predicting the sensory input is key to understanding imagined rotations. Mental imagery goes beyond prediction, rather, it involves the use of counterfactual queries in a probabilistic model. 


keywords          : Probabilistic graphical models, Particle filter, Embodied cognition, Vestibular cognition, Spatial perspective taking, Mental imagery
wordcount         : "X"

bibliography      : ["references.bib"]

figsintext        : yes
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

lang              : "english"
class             : "man"
# output            : papaja::apa6_word
output            : papaja::apa6_pdf
---

```{r message = FALSE, warning = FALSE}
library("papaja")
```



# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
