# head direction cells

[@Taube:2007fk]

- mental simulation cannot just er-use the state used in sensory inference, because the velocity is fed to the head directino cells. The brain would get confused

- directinal signal is not just a simple integration of velocity signals from the vestibular system
- signals from motor efferecence copy or proprioceptive systems appear to be crucial for upating the preferred firing direction over time
- what about this? you don't know where you are, because you were passively moved. Can you update if I tell you (verbally instruct you)?
- vestibular input is eesntial for establishing the head direction signal? How can we reconcile this with the assumption that re-afference is cancelled, i.e. input due to active motion is cancelled. Maybe it's the control model...

# Corollary discharge
[@Crapse:2008jc]


# Predictive control 
[@Stahl:2011dl]


- movemements can induce sensory input
- sensory input due to own actions is indistinguishable from input due to external forces
- strategy: efference copy -> corollary discharge

it seems intuitively obvious that this mechanism has something to do with mental imagery.
This has been pointed out many times; mental imagery and mental simulation more generelly is somehow related to the capacity to compute corollay discharge, based on the efference copy and a forward model.

> Necessary components:  efference copy and a forward model

Sensory receptors don't care about their input. The brain has to deal with the problem further downstream




```{r generate-data-1, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
dt <- 0.1
motiondata <-  generate_data(T = 2, frequency = 0.5,
                             amplitude = 20,
                             sensor_sd = 2.0)
# plot_trajectories(motiondata = motiondata)

motiondata_hidden <- motiondata %>%
    gather(type, value = value, -time) %>%
    filter(type != "observations") %>%
    mutate(type = factor(type,
                         levels = c("position",
                                    "velocity",
                                    "acceleration")))



p1 <- motiondata_hidden %>%
        ggplot(aes(x = time, y = value)) +
            geom_line(aes(linetype = type), size = 1.4) +
            geom_point(data = motiondata,
                       aes(x = time, y = observations),
                       shape = 21, colour = "white",
                       fill = "white", size = 6, stroke = 2) +
            geom_point(data = motiondata,
                       aes(x = time, y = observations),
                       shape = 21, colour = "black",
                       fill = "white", size = 4, stroke = 2) +
            guides(linetype = guide_legend(keywidth = 2.5, keyheight = 1)) +
            xlab("Time (sec)") +
            ylab("Angular position (deg)") +
            theme_apa() +
            theme(legend.title=element_blank())


motiondata_2 <-  generate_data(T = 2, frequency = 0.5,
                             amplitude = -20,
                             sensor_sd = 1.8)
# plot_trajectories(motiondata = motiondata)

motiondata_hidden_2 <- motiondata_2 %>%
    gather(type, value = value, -time) %>%
    filter(type != "observations") %>%
    mutate(type = factor(type,
                         levels = c("position",
                                    "velocity",
                                    "acceleration")))



p2 <- motiondata_hidden_2 %>%
        ggplot(aes(x = time, y = value)) +
            geom_line(aes(linetype = type), size = 1.4) +
            geom_point(data = motiondata_2,
                       aes(x = time, y = observations),
                       shape = 21, colour = "white",
                       fill = "white", size = 6, stroke = 2) +
            geom_point(data = motiondata_2,
                       aes(x = time, y = observations),
                       shape = 21, colour = "black",
                       fill = "white", size = 4, stroke = 2) +
            guides(linetype = guide_legend(keywidth = 2.5, keyheight = 1)) +
            xlab("Time (sec)") +
            ylab("Angular position (deg)") +
            theme_apa() +
            theme(legend.title=element_blank())

cowplot::plot_grid(p1, p2, nrow = 2, labels = c("a", "b"))
```
